const express=require('express')
const bodyparser=require('body-parser')
const cors=require('cors')
const morgan=require('morgan')
const {sequelize}=require('./models')
const app=express()
const config=require('./config/config')
app.use(morgan('combine'))
app.use(bodyparser.json())
app.use(cors())
require('./routes')(app)
require('./passport')
console.log("env")
sequelize.sync({force:false}).then(()=>{
    app.listen(config.port)
    console.log(`server started on port ${config.port}`)
})
